### ISSUE TITLE
Release v3.0 - ROAST V3.0 (codename: Hell's Kitchen)

### ISSUE THREAD

**Issue by tmedani** [andypotatohy/roast#20]
Hi Andy, 

Thanks again for this super work and this wonderful toolbox. 

I have a question related to this new release, maybe I missed something somewhere, but could you please specify what are the 'targeting feature added'. 
Or on another word what is the modifications and the new that we need to know in this version. 

Thanks in advance
Kind regards 
Takfarinas

**Comment by andypotatohy** [comment]
A new function roast_target() was added for doing targeted TES. Please refer to the releasing notes for more info. https://github.com/andypotatohy/roast/blob/v3.0/releasingNotes.txt

Maybe also sign up for the user group at roast-users@googlegroups.com.

**Comment by tmedani** [comment]
Super thank you!
I have just my emails and checked the discussions.
