### ISSUE TITLE
Matlab format for the NY head model

### ISSUE THREAD

**Issue by tmedani** [andypotatohy/roast#21]
Hi Andy, 

I'm trying to upload the volume mesh (tetra) of the NY head model from the https://www.parralab.org/nyhead/ 
However, I did not find any Matlab function to read correctly the Abaqus (.INP) or the Comsol (.MPHTXT)  file.
 
**Do you have a Matlab data file with these data (node, elem, face, tissue) as iso2mesh format?**

Also, I checked the brainstorm file, it contains only the lead field matrix and the head model is not included.
**Which method/soft did you use to compute the lead field matrix?**
**Is possible also to have the source space (cortex surface used as the source position)?** 

Thanks in advance. 

Takfarinas 

_PS : I'm working on the brainstorm project and we are testing roast for mesh generation, we will probably work closely in the next future on these parts._

**Comment by andypotatohy** [comment]
> Do you have a Matlab data file with these data (node, elem, face, tissue) as iso2mesh format?
No. You can generate that by calling roast('nyhead') and then you'll get the iso2mesh format mesh.

> Which method/soft did you use to compute the lead field matrix?
> Is possible also to have the source space (cortex surface used as the source position)?
On the nyhead webpage, the lead field was computed by Abaqus. The lead field was computed with current source placed on the scalp surface. Please refer to the NY head paper for details. 

Also please post your questions on the roast users Google group. The guy who did the brainstorm version of NY head is in that group who may answer your question better.

**Comment by tmedani** [comment]
Super thank you. 

I will post it on the Google group & re-check your paper.

Regards
