### ISSUE TITLE
Using only two different kinds of tissue (instead of six).

### ISSUE THREAD

**Issue by soeren-huebner** [andypotatohy/roast#27]
Hello all :)

I'm currently writing my master thesis in computer science and for this reason I'm trying to use Roast with some rather specifc input. My input is a simple, generated MRI which only contains two different kinds of tissue: a "blob" made from bone in the middle and some air around it. The following image illustrates this case:

![image](https://user-images.githubusercontent.com/68423342/97715738-0a60e800-1ac3-11eb-8cd9-bd60df498450.png)

I changed the hard-coded numberOfTissue variable in all the scripts and also adapted solveByGetDP.m to only consider air and bone. My problem now is that my "blob" gets mapped to some kind of default geometry when I let Roast run with the following parameters:

`roast('blob.nii', {'custom15',0.25, 'custom33',-0.25}, 'captype', 'egi', 'zeroPadding', 100);`

The electrodes shouldn't matter and the zeroPadding is needed because my "blob" is very small. This is the mapping I got in the mesh generation step:

![image](https://user-images.githubusercontent.com/68423342/97716205-a25ed180-1ac3-11eb-9eba-be7472adbaa9.png)

I want to compute the leadfield for my given geometry. Is there a way to achieve this with Roast?

Thanks in advance!
Sören

**Comment by andypotatohy** [comment]
Hi @soeren-huebner, thanks for trying on your project, very interesting. Here's my advice:

1) I think you already have your segmentation of bone and air as shown in the 1st figure? So you do not need to run ROAST from very beginning, as ROAST uses SPM to segment, and SPM was designed to segment the complicated head geometry.
2) Electrode placement will totally fail for your problem, as it was designed to place electrodes on a human head, not your "blob" of bone and air. You will have to manually do this or write your own code.
3) once you have placed the electrodes, you can interface with ROAST to load your segmentation (with electrodes) and do the rest (meshing and solving). You will have to change many code related to tissue class in the meshing and solving code.

Hope this helps.
