### ISSUE TITLE
electrodes inside the volume.

### ISSUE THREAD

**Issue by tmedani** [andypotatohy/roast#28]
Hello @andypotatohy, 

I hope you are doing well & happy new year. 

I'm just wondering if it's possible to use roast with a scenario where both the stimulation electrode and the reference electrode are both inside the volume of the head (inside the mesh)?

Any recommendations, links?

Thank you in advance. 

Best,
Takfarinas

**Comment by andypotatohy** [comment]
Hi @tmedani ,

Happy new year! For your scenario, roast was not designed for that. But of course you can do it. You can specify any mesh node inside the mesh to be anode and cathode, but you have to tweak the code. It's just changing the boundary conditions.

Hope this helps.

**Comment by tmedani** [comment]
Great, thanks for your quick answer, 
so for the code changing is it related only on the Matlab side of Roats, 
or also some change should be applied to the FEM solver?

**Comment by andypotatohy** [comment]
It should be only the Matlab side, i.e., just the code in defining boundary condition in prepareForGetDP.m and generating the .pro file for getDP in solveByGetDP.m

**Comment by tmedani** [comment]
Thanks, 

I will check all that asap, and I will let you know. 

Best,
