### ISSUE TITLE
Current flow density instead of electrical field on the volume

### ISSUE THREAD

**Issue by tmedani** [andypotatohy/roast#29]
Hi @andypotatohy, 

Is it possible to display the current flow on the volume instead of the electrical field? 
does Roast compute and save the current?

I guess it can possible to convert the electrical field to current by Ohm's law on the volume,
but I'm not sure if it's doable and how to manipulate the output data in order to do it correctly. 

Thanks in advance for your reply. 

Best,

**Comment by andypotatohy** [comment]
Yes of course you can convert the E-field to current density by multiplying the conductivity values. It's straightforward for isotropic conductivity: you just need to multiply the volume of E-field by the conductivity volume. You will need to use the segmentation masks to assign the proper conductivity for each tissue.

Hope this answer your question.

**Comment by tmedani** [comment]
Yes, this answer my questions, thanks, 

furthermore, if I understand it well from your answer, we can also use the anisotropic tensors?
if we have the tensor for each voxel, instead of scaling the electric field vector by the iso conductivity,
we will multiply it by the tensor, right? then we can have the current distribution for an anisotropic volume?

Thanks again for your helpful answers. 

best,

**Comment by andypotatohy** [comment]
Yes, you can multiply the anisotropic tensor. But the E-field is computed from assuming the conductivity values are isotropic, so I don't think by multiplying with anisotropic conductivity will give you accurate results. The anisotropic conductivity should be included in the solving process. I will add anisotropic modeling if ROAST is further funded.

**Comment by tmedani** [comment]
Indeed, you are right, we need to check at some point the FEM linear system. 
anyway, I'm more interested in the isotropic case right now. 

We cross our fingers for your grant and looking forward to the new feature and further integrations for Roast. 

Thanks again for your clear answers.

A+
