### ISSUE TITLE
Reference point/electrode for the TES simulation

### ISSUE THREAD

**Issue by tmedani** [andypotatohy/roast#30]
Hi Andy, 

Which point is considered as the reference of the electrical potential in Roast, 
and how it's defined during the process of solving the Laplace equation?  

Also, how can we find the reference point on the final results? 

In the following, I have a basic example, with anode and cathode on the top of the head, 
How can I find the reference point for the potential?  

![image](https://user-images.githubusercontent.com/37831900/105820201-1814f500-5f6e-11eb-9fed-19bedda26dfb.png)
 
![image](https://user-images.githubusercontent.com/37831900/105820294-3d096800-5f6e-11eb-8355-14a6d647060a.png)

Thanks in advance.

Best,

**Comment by andypotatohy** [comment]
I'm not sure / don't remember how getDP picks the reference for the voltage, but I re-referenced the voltages to the point that has the minimal voltage value, see this line https://github.com/andypotatohy/roast/blob/7cd31ff315a45b875d7dc85634243b4266db314b/postGetDP.m#L34

Hope this helps.

**Comment by tmedani** [comment]
Thanks, Andy, 
it makes sense to re-reference it to the lowest point, which I guess is the point where is the lowest current (the sink). 

But I'm missing some point, maybe I'm wrong, why there is no zero voltage in the color bar? 
we should have it, or no?

Thanks again.

**Comment by andypotatohy** [comment]
The re-reference was done on the point cloud, but the figure you're looking at shows the voltage in the 3D volume, which is after interpolating the voltages from the point cloud, so maybe the sink is not exactly the same as in the point cloud. You can look up the exact location of the sink if you open the .pos file for the voltage and look for the minimal voltage there, which is the sink.

**Comment by tmedani** [comment]
Hi Andy, 

Just a quick comment, I changed the line

`C{2} = C{2} - min(C{2}); % re-reference the voltage
`
to 

`C{2} = C{2} - mean(C{2}); % re-reference the voltage to the mean value
`
and the results look much better for interpretation, the zero line is clear in the image and the values are ~symetric.

![image](https://user-images.githubusercontent.com/37831900/107694774-9ce95980-6c64-11eb-844a-e1349109c8da.png)

Thanks

Takfarinas
