### ISSUE TITLE
Output results visualisation with gmsh

### ISSUE THREAD

**Issue by tmedani** [andypotatohy/roast#31]
Hi Andy, 

I'm just wondering if it's possible to use Gmsh to visualize the outputs of the solver? 

Have you tried it before? 

Thanks in advance.
Takfarinas

**Comment by andypotatohy** [comment]
yes of course. Gmsh is part of a bigger ecosystem of onelab http://onelab.info/  So you can use that to visualize. The .pos format is also compatible with Gmsh, I believe.

Hope this helps.

**Comment by tmedani** [comment]
Thanks, I will give it a try.
