### ISSUE TITLE
Node not found and output .pos files all have NaN

### ISSUE THREAD

**Issue by djmountainman** [andypotatohy/roast#35]
Dear @andypotatohy,

First, thank you for the open source code. I look forward to using it! 

Ran the code twice once without the zeropadding and the most recent one with it. I used my own T2. Please see below:

roast('insert\generic\path\name\here/WIPSAG_T1W_3D_2.nii',{'C3',2,'Fp2',-2},'zeropadding',60,'electype','pad','elecsize',[50 50 3])   

At the end of processing (Step 5) I got a wall of text that read, "Warning : Node (137.818,218.691,255.767) not found." This was only 1 of the lines of text. Additionally, when I opened the output text files (.pos) all values were NaN. Finally, I received the following error, 

"Error using matlab.graphics.axis.Axes/set
Error setting property 'CLim' of class 'Axes':
Value must be a 1x2 vector of numeric type in which
the second element is larger than the first and may be
Inf
Error in caxis (line 106)
            set(ax,'CLim',arg);
Error in visualizeRes (line 131)
    caxis(dataShowRange);
Error in roast (line 858)
        visualizeRes(subj,subjRasRSPD,T2,node,elem,face,injectCurrent,hdrInfo,uniqueTag,0,vol_all,ef_mag,ef_all);"

Any help would be appreciated! Thank you

**Comment by andypotatohy** [comment]
Hi, this is a recurring issue. Please search the ROAST mailing list. For example, https://groups.google.com/g/roast-users/c/2JfUpyLLNQE/m/wkA-95dfBAAJ

**Comment by djmountainman** [comment]
Thanks for the replay. Changing the mesh options made it work!

 "Increase of meshOpt.distbound from 0.3 (default) to 0.5 solved the problem"
