### ISSUE TITLE
Extra tissue type

### ISSUE THREAD

**Issue by StephenHogg** [andypotatohy/roast#36]
Hi @andypotatohy ,

Thanks for making ROAST - I'm doing some work at the moment that involves the calculation of E fields but I have an extra tissue type I'm interested in. If I know the conductivity and can add it on to a segmented voxel field, is it possible to include it in the calculation of the E field? If so, how would this be done?

Regards,

Stephen

**Comment by andypotatohy** [comment]
Yes it's possible, but you have to change a lot of code, as now it's hard coded to be 6 tissue types (plus electrodes and gel). You will need to change functions related to meshing and solving. I wish I had time to write developer documentation so that it can help you better.
