### ISSUE TITLE
Problem custom electrodes location

### ISSUE THREAD

**Issue by EFraats** [andypotatohy/roast#41]
Hi all,

I have a problem with making a customized electrode position to enter in ROAST.

**My code:**

``roast('example/subject1.nii',{'custom_A13_A18',2,'custom_A12_A19',-0.5,'custom_A18_A21',-0.5, 'custom_A14_A17', -0.5, 'custom_A10_A13', -0.5},'electype','ring', 'capType', '1020')``

**Content of text file with electrode locations**:

custom_A13_A18 -63.402 -29.119 6.109
custom_A12_A19 -33.982 -41.116 4.977
custom_A18_A21 -57.533 -71.481 5.016
custom_A14_A17 -79.854 -35.060 2.271
custom_A10_A13 -61.596 6.138 `6.165

**Error**

Error using elecPreproc (line 41)
You specified customized electrode locations but did not provide the location coordinates. Please put together all the coordinates in a text file 'subjectName_customLocations'
and store it under the subject folder.

Error in roast (line 674)
[elecPara,indInUsrInput] = elecPreproc(subj,elecName,elecPara);

Error in ROAST_matlab_Fraats (line 85)
roast('example/subject1.nii',{'custom_A13_A18',2,'custom_A12_A19',-0.5,'custom_A18_A21',-0.5, 'custom_A14_A17', -0.5, 'custom_A10_A13', -0.5},'electype','ring', 'capType',
'1020')

**Screenshot of folder structure**
![image](https://github.com/andypotatohy/roast/assets/169881495/b3eac403-9719-4199-8b6f-e018e9bf48c5)

Does someone have an idea what is going on?

**Comment by andypotatohy** [comment]
Hi, it's a path problem. You put the text file under roast-master, but you called roast as roast('example/subject1.nii' ...). You should call it like roast('subject1.nii'...). Hope this helps.
